[local]
localhost

[mongodb]
localhost

[catalogue]
catalougue-dev.ptdevops.online

[redis]
localhost

[user]
user-dev.ptdevops.online

[cart]
cart-dev.ptdevops.online

[frontend]
frontend-dev.ptdevops.online

[payment]
payment-dev.ptdevops.online

[mysql]
localhost

[rabbitmq]
localhost

[shipping]
shipping-dev.ptdevops.online  