[local]
localhost

[mongodb]
mongodb-dev.ptdevops.online

[catalogue]
catalougue-dev.ptdevops.online

[redis]
redis-dev.ptdevops.online

[user]
user-dev.ptdevops.online

[cart]
cart-dev.ptdevops.online

[frontend]
frontend-dev.ptdevops.online

[payment]
payment-dev.ptdevops.online

[mysql]
mysql-dev.ptdevops.online

[rabbitmq]
rabbitmq-dev.ptdevops.online

[shipping]
shipping-dev.ptdevops.online  